compatibility_date = "2022-02-21"
compatibility_flags = ["nodejs_compat_v2"]
main = "app/app.ts"
name = "graphql-workers-subscriptions"
workers_dev = true

# [build]
# command = "npm run build"

[[migrations]]
new_classes = ["WsConnection"]
tag = "v1"
[[migrations]]
deleted_classes = ["WsConnection"]
new_classes = ["WsConnectionPool"]
tag = "v2"

[[d1_databases]]
binding = "SUBSCRIPTIONS" # available in your Worker on env.SUBSCRIPTIONS
database_name = "SUBSCRIPTIONS"

database_id = "xxxxx"
migrations_dir = "node_modules/graphql-workers-subscriptions/migrations"
preview_database_id = "xxxx"


# [miniflare]
# durable_objects_persist = true

[durable_objects]
bindings = [{name = "WS_CONNECTION_POOL", class_name = "WsConnectionPool"}]

# To create the database and table, run:
# wrangler d1 migrations apply SUBSCRIPTIONS
